immuni-app/immuni-app-android

app/build.gradle
=> fix: Remove duplicated annotation

README.md
Add CI badge so it's possible to glance over the readme to check the build status of the app.
=> feat: Add CI badge.

app/src/main/java/it/ministerodellasalute/immuni/ui/ImmuniActivity.kt
For privacy reason we prevent the users to take screenshots.
=> feat: disable screenshots to preserve privacy

extensions/src/main/java/it/ministerodellasalute/immuni/extensions/http/TrafficAnalysisPreventionHeadersInterceptor.kt, network/src/main/java/it/ministerodellasalute/immuni/network/api/NetworkRetrofit.kt
- changes the default headers to make them consistent across all the network calls
=> feat: traffic analysis prevention using fixed headers size

app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/OnboardingViewModel.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/privacy/PrivacyDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/settings/SettingsViewModel.kt
- Removes WebView usage in favor of external browser
=> feat: open web pages in the external web browser

app/build.gradle, app/src/main/java/it/ministerodellasalute/immuni/ImmuniApplication.kt, app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/api/services/ExposureIngestionService.kt, app/src/main/java/it/ministerodellasalute/immuni/config/ExposureIngestionNetworkConfiguration.kt, app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/models/ExposureStatus.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/repositories/ExposureIngestionRepository.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/worker/WorkerManager.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/faq/FaqDetailsDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/DummyExposureIngestionWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/test/java/it/ministerodellasalute/immuni/repositories/ExposureIngestionRepositoryTest.kt, app/src/test/java/it/ministerodellasalute/immuni/workers/DummyExposureIngestionWorkerTest.kt, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/utils/RandomUtils.kt, network/src/main/java/it/ministerodellasalute/immuni/network/api/NetworkRetrofit.kt
This PR implements the dummy calls and data padding for ingestion service
=> feat: dummy calls and data padding for ingestion service

app/src/main/java/it/ministerodellasalute/immuni/config/ExposureIngestionNetworkConfiguration.kt, network/src/main/java/it/ministerodellasalute/immuni/network/api/NetworkRetrofit.kt
This fix a regression where the content type was stripped off the http request.
=> fix: add http request content type

app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/suggestions/StateCloseDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/suggestions/StateCloseViewModel.kt, app/src/main/res/values/strings.xml
Add contact date in close contact suggestions page
=> feature: add contact date in suggestions page

app/src/main/res/layout/faq_fragment.xml, app/src/main/res/layout/onboarding_privacy_fragment.xml, app/src/main/res/layout/onboarding_province_fragment.xml, app/src/main/res/layout/otp_fragment.xml, app/src/main/res/layout/popup_dialog.xml, app/src/main/res/layout/popup_recycler_view_dialog.xml, app/src/main/res/layout/state_close_dialog.xml, app/src/main/res/layout/state_default_dialog.xml, app/src/main/res/layout/state_positive_dialog.xml, app/src/main/res/layout/upload_data_fragment.xml
Add content description to close and back navigation buttons.
=> fix: add accessibility description to navigation buttons

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
This PR updates the default Italian and English FAQs.
=> fix: update default Italian and English FAQs

app/src/main/java/it/ministerodellasalute/immuni/ImmuniApplication.kt, app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/worker/WorkerManager.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/DummyExposureIngestionWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ServiceNotActiveNotificationWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/models/ServiceNotActiveNotificationWorkerStatus.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/repositories/ServiceNotActiveNotificationWorkerRepository.kt, app/src/test/java/it/ministerodellasalute/immuni/workers/ServiceNotActiveNotificationWorkerTest.kt
fix: typo in class
fix: service not active notification logic
=> fix: service not active notification logic and typo

app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/storage/KVStorage.kt
This PR removes KVStorage "state" singleton, and replace it with ad-hoc KVStorage instances
=> feat: remove KVStorage "state" singleton, and replace it with ad-hoc KVStorage instances

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
This PR updates the copy of the default English FAQs.
=> fix: copy of default English FAQs

app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Fix copy, remove extra escaping characters.
=> fix: remove extra escaping characters in strings

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
=> chore: update default FAQs

app/src/main/res/values/strings.xml
=> feat: update pilot project copy

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/ViewPagerAdapter.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/ViewPagerFragment.kt
This PR plugs the configuration to show/hide the pilot page
=> feat: add feature flag to show/hide the experimental phase page

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
Update exposure configuration default parameters
=> chore: update exposure default configuration

app/src/main/java/it/ministerodellasalute/immuni/ui/home/HomeDiffCallback.kt
Fix the glitch in the button when return to home screen
=> fix: recycler view home diff callback

app/src/main/java/it/ministerodellasalute/immuni/ui/suggestions/StateCloseDialogFragment.kt, app/src/main/res/layout/disable_exposure_api_dialog.xml, app/src/main/res/layout/state_close_dialog.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
=> feat: update localisations

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
=> fix: localisation

app/src/main/java/it/ministerodellasalute/immuni/api/services/ExposureIngestionService.kt
Update “Trentino Alto Adige/Südtirol” and “Bolzano/Bozen”
=> feat: add german version for Trentino Alto Adige/Südtirol and Bolzano/Bozen

app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/dialogs/LocalisationExplanationDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/viewpager/ExposureNotificationFragment.kt, app/src/main/res/layout/localisation_explanation_dialog.xml, app/src/main/res/layout/state_close_dialog.xml, app/src/main/res/navigation/onboarding.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
Update copy, minor layout changes and add localisation explanation dialog during onboarding.
=> feat: add localisation explanation popup and update copy

app/src/main/java/it/ministerodellasalute/immuni/logic/notifications/AppNotificationManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/worker/WorkerManager.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/DummyExposureIngestionWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ForceUpdateNotificationWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/NotificationsCleanerWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/OnboardingNotCompletedWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/RiskReminderWorker.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ServiceNotActiveNotificationWorker.kt
Add debugging notification group to show background tasks events with timestamp.
=> feat: debugging notification group

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/home/HomeListAdapter.kt
Update default tos and pp urls. 
Show explanations popup on shield animation click.
=> feat: ux updates

app/src/main/java/it/ministerodellasalute/immuni/ui/welcome/WelcomeFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/welcome/WelcomeItemFragment.kt, app/src/main/res/layout/welcome_fragment.xml, app/src/main/res/layout/welcome_item_fragment.xml, app/src/main/res/values-it/strings.xml
- Moves "Find out about the app" CTA outside Carousel for better welcome experience
- ...
- ...
In particular, the ...
=> feat: polish welcome view

app/src/main/java/it/ministerodellasalute/immuni/ui/main/MainViewModel.kt
- Swaps Home Card (howItWorks and SelfCare) positions
In particular, the ...
=> chore: swap home howItWorks and selfCare tiles

app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/repositories/ExposureReportingRepository.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/support/SupportDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/support/SupportViewModel.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/main/res/layout/support_dialog.xml, app/src/main/res/values/strings.xml
- Adds Last Check date
In particular, the ...
=> feat: add customer support info 

app/src/main/java/it/ministerodellasalute/immuni/ui/support/SupportViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/it/ministerodellasalute/immuni/strings/StringResourcesTest.kt
=> feat: add translations and unit test

app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/OnboardingViewModel.kt
In "Change province" page now the current province is checked.
- Fixes #236
=> fix: show current province in change province page

app/src/main/java/it/ministerodellasalute/immuni/logic/notifications/AppNotificationManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/worker/WorkerManager.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/main/res/values/strings.xml, build.gradle
In this PR we are removing the foreground service notifications and vibrations.
- Fixes #268
=> fix: disable fetch service vibration and notifications

app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureAnalyticsManager.kt, app/src/test/java/it/ministerodellasalute/immuni/logic/exposure/ExposureAnalyticsManagerTest.kt
In this fix we avoid to send the analytics when matched keys are below the threshold. The threshold is inside the configuration settings in the `exposureInfoMinimumRiskScore` property.
=> fix: avoid to send analytics when matched keys are below the threshold

app/src/main/java/it/ministerodellasalute/immuni/api/services/ExposureAnalyticsService.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/CountriesOfInterestManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureAnalyticsManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureDataMapping.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/repositories/ExposureReportingRepository.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/countriesofinterest/CountriesFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/test/java/it/ministerodellasalute/immuni/logic/exposure/ExposureRepositoryTest.kt, build.gradle
This PR add the build number in the analytics operational info request.
=> feat: add build number in operational info requests

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/CountriesOfInterestManager.kt, app/src/main/res/layout/countries_of_interest.xml, app/src/main/res/values/strings.xml
- Added Croatia
- Changed in italian Olanda -> Paesi Bassi
- Spead to Spread
=> fix: changed label, add sort and padding to list

app/src/main/java/it/ministerodellasalute/immuni/ui/cun/CunViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
=> fix: change of cun error messages

app/build.gradle
=> fix: crash on android 7.x #333

app/src/main/java/it/ministerodellasalute/immuni/logic/greencovidcertificate/DecodeData.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/greencertificate/GenerateGreenCertificate.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/greencertificate/MoreDetailGreenCertificate.kt, app/src/main/res/values/strings.xml
=> Version 2.5.1

app/src/main/res/layout/green_certificate_tab.xml, build.gradle
- EU digital covid certificate: fix QR code layout
=> fix: layout qrcode and upgrade version

build.gradle, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/storage/KVStorage.kt
- Fix deprecated method KVStorage
=> fix: KVStorage deprecated and upgrade security library version

build.gradle, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/storage/KVStorage.kt
- KVStorage deprecated and upgrade security library version
=> KVStorage deprecated and upgrade security library version

app/src/main/res/layout/green_certificate_tab.xml, build.gradle, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/storage/KVStorage.kt
=> Fix deprecated KVStorage

app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/OnboardingViewModel.kt, build.gradle, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/storage/KVStorage.kt
- manage Green Certificate after province change
=> fix: manage Green Certificate after province change

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/greencertificate/MoreDetailGreenCertificate.kt, app/src/main/res/layout/green_certificate_more_details_test.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, build.gradle
=> Eudcc Expiration

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/greencertificate/MoreDetailGreenCertificate.kt, app/src/main/res/layout/green_certificate_more_details_recovery.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, build.gradle
=> feat: upgrade to Api 30

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/greencertificate/MoreDetailGreenCertificate.kt, app/src/main/res/layout/green_certificate_more_details_recovery.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, build.gradle
=> feat: upgrade to Api 30 huawei

README.md
Removed "Backend Services" link from ToC because it's a dead link
=> Removed broken link from README.md

debugmenu/src/main/java/it/ministerodellasalute/immuni/debugmenu/ui/ExitActivity.kt
Just fixing a typo in the code documentation
=> fix: Fixed typo in the ExitActivity KDoc string

README.md
- the broken link in README as described by #270
- Fixes #270
=> fix: broken link in README#checking-the-build
