dangerfile.ts, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/utils/Log.kt, network/src/main/java/it/ministerodellasalute/immuni/network/api/NetworkRetrofit.kt
Disable production logs for security reason.
- add handy log extension function
- disable logging in release builds
=> fix: log only in debug builds

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/settings/ConfigurationSettingsManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/settings/repositories/ConfigurationSettingsStoreRepository.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/user/UserManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/user/repositories/UserRepository.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/ImmuniActivity.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/faq/FaqFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/faq/FaqViewModel.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/setup/SetupFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/setup/SetupViewModel.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/welcome/WelcomeFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ExposureNotificationWorkers.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/ForceUpdateNotificationWorker.kt, app/src/test/java/it/ministerodellasalute/immuni/ui/setup/SetupViewModelTest.kt
This PR:
- removes the fetching of `ConfigurationSettings` upon each Activity resume;
- provides default FAQs that will be used when FAQs haven't yet been successfully downloaded from the URLs retrieved with the `ConfigurationSettings`;
- makes so that a fetch of FAQs gets automatically triggered upon a successful `ConfigurationSettings` retrieval;
- triggers a `ConfigurationSettings` fetch at the first app launch;
- simplifies `FaqFragment` and `FaqViewModel` as they do not need to handle the fetching of the 
FAQs and relative error anymore;
=> feat: avoid fetching ConfigurationSettings in foreground sessions, and provide default FAQs

app/src/main/java/it/ministerodellasalute/immuni/ui/ImmuniActivity.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/viewpager/ViewPagerBaseFragment.kt, app/src/main/res/layout/onboarding_bluetooth_fragment.xml, app/src/main/res/layout/onboarding_exposure_fragment.xml, app/src/main/res/layout/onboarding_notifications_fragment.xml, app/src/main/res/layout/onboarding_phishing_warning.xml, app/src/main/res/layout/onboarding_protect_device_fragment.xml, app/src/main/res/values/strings.xml
All the onboarding pages now have a scrolling behaviour. The top image can fit at max the 50% of the screen height.
In particular, this is necessary for the Exposure API page where the explanation text is longer. And in general for accessibility and localisation common issues.
- [] I have written new tests for my core changes, as applicable.
=> refactor: onboarding layout with scrollable behaviour

app/src/main/java/it/ministerodellasalute/immuni/ui/faq/FaqDetailsDialogFragment.kt
This fix the FAQ descriptions not being wrapped correctly.
- Fixes #68
=> fix: faq descriptions are not in HTML format, but plain text

app/src/main/java/it/ministerodellasalute/immuni/ui/faq/FaqDetailsDialogFragment.kt, debugmenu/src/main/java/it/ministerodellasalute/immuni/debugmenu/DebugMenuTouchManager.kt
In production release there is no need to alloe the debug menu to be triggered.
=> refactor: disable production triggering of debug menu

app/src/androidTest/java/it/ministerodellasalute/immuni/nearby/KeyMatchingTests.kt, app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/home/HomeListAdapter.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/main/MainViewModel.kt, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/nearby/ExposureNotificationManager.kt
The Exposure Manger used a separated app lifecycle object causing the SDK state to not be triggered.
- Fixes #86
=> fix: app lifecycle

.circleci/config.yml
This PR improves the execution of PR checks on forked PRs. 
In the previous implementation of the scheduler system, PR checks on forked PRs were executed by identifying _unauthorised_ workflows and scheduling a re-run with the necessary settings to run Danger. However, due to limitations of CircleCI, such workflows may not be unauthorised in the first place, or may not have access to the necessary settings even after they're re-scheduled. This may result in Danger checks not being run on certain forked PRs, which limits our ability to maintain a consistent coding style and give constructive feedbacks to the community.
To solve this issue, we propose a different approach in which Danger is executed directly by the scheduler workflow for all forked PRs, regardless of the authorisation …
=> [WIP] [FEAT] Enable danger on forked PRs within scheduler

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/settings/ConfigurationSettingsManager.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/settings/SettingsViewModel.kt, app/src/test/java/it/ministerodellasalute/immuni/logic/ConfigurationSettingsManagerTest.kt
This PR makes the app robust to eventual future language additions
=> fix: make app robust to eventual future language additions

extensions/src/main/java/it/ministerodellasalute/immuni/extensions/nearby/ExposureNotificationManager.kt
This PR fixes a bug where the user cannot deny the TEKs sharing permission and then retry to upload them.
=> fix: upload teks retry

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
The default maps were initialised with uppercase keys, but should be lowercase.
=> fix: error in default languages map keys

app/src/main/java/it/ministerodellasalute/immuni/ui/otp/OtpFragment.kt
Hide OTP validation error message after the timer expires.
- Fixes #101
=> fix: hide OTP error message when the timer expires

app/src/main/res/values/styles.xml
By default material alert dialogs set a maximum of 2 lines to alert titles.
- remove singleLine attribute to alert dialog titles
- set maxLines to 6 instead of 2
#99
=> fix: truncated alert titles

app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/OnboardingViewModel.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/viewpager/ExposureNotificationFragment.kt
In some corner case scenario the device has the most recent Google Play Services installed, but the exposure notification module is not yet ready to be used. The user is blocked during the onboarding.
This PR add more specific error messages with error code to help the user, but also the developers to debug.
=> fix: better google play services error messages

extensions/src/main/java/it/ministerodellasalute/immuni/extensions/utils/MemoryUtils.kt
Lottie animation in "How it works" section are quite demanding.
In particular, this PR uses Lottie animations only on very high end devices while it shows illustrations on the other devices.
=> fix: enable Lottie animation in scroll view only on high end devices

app/src/main/java/it/ministerodellasalute/immuni/ui/howitworks/HowItWorksDialogFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/howitworks/HowItWorksListAdapter.kt, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/utils/MemoryUtils.kt
To avoid lag we pause Lottie animation while the recycler view is scrolling.
In this way we can support animations also on low end devices.
=> fix: pause animations while scrolling

app/src/main/java/it/ministerodellasalute/immuni/ImmuniApplication.kt
This PR fixes possible crashes due to the use of `UnsafeLazyImpl` by Koin's `inject()`, by eagerly initializing `UserManager` and `WorkerManager` in `ImmuniApplication`.
=> fix: eagerly initialize UserManager and WorkerManager to prevent possible crashes

app/src/test/java/it/ministerodellasalute/immuni/strings/StringResourcesTest.kt, app/src/test/java/it/ministerodellasalute/immuni/testutils/XmlUtils.kt
Translations are error prone by nature, in particular the placeholders. This PR adds some unit tests that check for correct placeholders in all locales.
=> test: add string placeholders unit tests

app/src/main/java/it/ministerodellasalute/immuni/koinModule.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/exposure/ExposureManager.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/notifications/AppNotificationManager.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/viewpager/ExposureNotificationFragment.kt
Notifications are now not sticky. The user can dismiss them immediately without the need to click on them.
As soon as the user deactivate the service, a warning notification pops up. 
As soon the user re-activate the service from within the app, the notification disappears.
- Fixes #200 
- Fixes #204
=> feat: change notifications dismiss logic

app/src/main/java/it/ministerodellasalute/immuni/ImmuniApplication.kt, app/src/main/java/it/ministerodellasalute/immuni/logic/worker/WorkerManager.kt, app/src/main/java/it/ministerodellasalute/immuni/workers/NotificationsCleanerWorker.kt
Add a periodic worker to cleanup notifications (force update, finish onboarding and service not active).
In addition the notifications are cleaned up at every app foreground event.
=> feat: clear notifications

app/src/main/java/it/ministerodellasalute/immuni/ui/home/HomeFragment.kt
Remove unnecessary and misleading app exit confirmation dialog.
- Fixes #137
=> fix: remove app exit confirmation

app/src/main/java/it/ministerodellasalute/immuni/ui/dialog/BottomSheetDialogDarkFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/dialog/BottomSheetDialogLightFragment.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/main/MainActivity.kt, app/src/main/java/it/ministerodellasalute/immuni/ui/onboarding/fragments/viewpager/ExposureNotificationFragment.kt, app/src/main/res/layout/onboarding_exposure_fragment.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/styles.xml, build.gradle, extensions/src/main/java/it/ministerodellasalute/immuni/extensions/nearby/ExposureNotificationManager.kt
On Android 11  users are able to use Exposure Notification apps without turning on the device location setting. See details [here](https://blog.google/inside-google/company-announcements/update-exposure-notifications).
The app doesn't check anymore for active location on Android 11 and up.
The app doesn't display location specific message to the user on Android 11 and up.
=> feat: remove location requirement for Android 11 and up

app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt
Align default settings with the ones returned by the settings [API](https://get.immuni.gov.it/v1/settings?platform=android&build=1).
=> fix: align default settings with the ones returned by the settings API

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
As mentioned in #314 users might feel confused when they try to run Immuni in a secondary profile or in a work profile. This PR adds a phrase to inform users that Exposure Notification APIs only work on primary profile
⚠️ This warning is only available for English and Italian languages, I need some help with other translations.
=> Add label to inform users that Exposure Notification APIs only work on primary profile

extensions/src/main/java/it/ministerodellasalute/immuni/extensions/playstore/PlayStoreActions.kt
Seems like `PlayStoreActions` is using as fallback a plain `http://` URL
if the `market://` intent fails to resolve.
I've checked all the other occurrences and they're fine.
Fixes #46
Closes #47
=> fix: Do not fallback to a plain http URL in PlayStoreActions

README.md
Signed-off-by: enricocid <enrico2588@gmail.com>
This little mod fixes the broken link in "authors / copyright" header.
This PR tackles: na
na
- Fixes na
=> fix: authors/copyright link in readme
